### ISSUE TITLE
covariance_matrix_plot runcard fails when executing procs_chi2_table 

### ISSUE THREAD

**Issue by andreab1997** [NNPDF/nnpdf#1520]
Running the covariance_matrix_plot runcard fails when entering in the function `groups_chi2_table` https://github.com/NNPDF/nnpdf/blob/9840fc69dfcbcf25ebb30236916c4f1fc65a1785/validphys2/src/validphys/results.py#L666  This could be linked to the wrong shape of `groups_each_dataset_chi2` as constructed by https://github.com/NNPDF/nnpdf/blob/9840fc69dfcbcf25ebb30236916c4f1fc65a1785/validphys2/src/validphys/results.py#L663

**Comment by scarlehoff** [comment]
Note that interestingly enough, `groups_data` is grouped correctly instead:

https://github.com/NNPDF/nnpdf/blob/9840fc69dfcbcf25ebb30236916c4f1fc65a1785/validphys2/src/validphys/results.py#L803

despise using exactly the same `collect` syntax! I guess we need @Zaharid for this one.

**Comment by andreab1997** [comment]
Runcard to reproduce the error:
[covariance_matrix_plots_7pt_reduced.txt](https://github.com/NNPDF/nnpdf/files/8080453/covariance_matrix_plots_7pt_reduced.txt)

**Comment by Zaharid** [comment]
I tried reproducing this and got the error

```python-traceboack
Traceback (most recent call last):
  File "/home/zk261/data2/miniconda3/envs/nnpdfdev/bin/validphys", line 33, in <module>
    sys.exit(load_entry_point('validphys', 'console_scripts', 'validphys')())
  File "/mhome/damtp/s/zk261/nnpdf/validphys2/src/validphys/scripts/main.py", line 10, in main
    vp.main()
  File "/mhome/damtp/s/zk261/nnpdf/validphys2/src/validphys/app.py", line 161, in main
    a.main()
  File "/home/zk261/data2/miniconda3/envs/nnpdfdev/lib/python3.9/site-packages/reportengine/app.py", line 395, in main
    self.run()
  File "/mhome/damtp/s/zk261/nnpdf/validphys2/src/validphys/app.py", line 156, in run
    super().run()
  File "/home/zk261/data2/miniconda3/envs/nnpdfdev/lib/python3.9/site-packages/reportengine/app.py", line 380, in run
    rb.execute_sequential()
  File "/home/zk261/data2/miniconda3/envs/nnpdfdev/lib/python3.9/site-packages/reportengine/resourcebuilder.py", line 166, in execute_sequential
    result = self.get_result(callspec.function,
  File "/home/zk261/data2/miniconda3/envs/nnpdfdev/lib/python3.9/site-packages/reportengine/resourcebuilder.py", line 175, in get_result
    fres =  function(**kwdict)
  File "/mhome/damtp/s/zk261/nnpdf/validphys2/src/validphys/results.py", line 685, in procs_chi2_table
    return groups_chi2_table(procs_data, pdf, procs_chi2, each_dataset_chi2)
  File "/mhome/damtp/s/zk261/nnpdf/validphys2/src/validphys/results.py", line 677, in groups_chi2_table
    stats = chi2_stats(dsres)
  File "/mhome/damtp/s/zk261/nnpdf/validphys2/src/validphys/results.py", line 785, in chi2_stats
    rep_data, central_result, npoints = abs_chi2_data
TypeError: cannot unpack non-iterable MCStats object
```

Is that it?

**Comment by scarlehoff** [comment]
Yes. If you inspect the error you will see that the reason is that the grouping of the input arguments seems to be different (despite having similar `collect`)

**Comment by Zaharid** [comment]
```
def procs_index(procs_data):
    return groups_index(procs_data)
```

This looks like it should be `return groups_index(procs_data[0])`

**Comment by scarlehoff** [comment]
The problem is that the list contains all dataset in the runcard, with no grouping, so if you do that the dataset you use has no connection with the ones you get on the other two arguments.

If you do that the code "works" because zips stop when one of the lists finishes and by construction the subgroups will always be smaller than the full dataset list.

**Comment by Zaharid** [comment]
I see that `groups_chi2_table` takes `groups_each_dataset_chi2` while `procs_chi2_table` takes `each_dataset_chi2`, which seems wrong.

**Comment by Zaharid** [comment]
After I fix that one as

https://github.com/NNPDF/nnpdf/commit/cf4e3eb055075845e5efb26946c5cb7ebac8febc

there are still problems in various other places, e.g.

```python-traceback
  File "/mhome/damtp/s/zk261/nnpdf/validphys2/src/validphys/theorycovariance/output.py", line 32, in procs_chi2_table_theory
    return groups_chi2_table(
  File "/mhome/damtp/s/zk261/nnpdf/validphys2/src/validphys/results.py", line 675, in groups_chi2_table
    stats = chi2_stats(dsres)
  File "/mhome/damtp/s/zk261/nnpdf/validphys2/src/validphys/results.py", line 781, in chi2_stats
    rep_data, central_result, npoints = abs_chi2_data
TypeError: cannot unpack non-iterable MCStats object
```

**Comment by Zaharid** [comment]
FWIW what broke these things was
79604bdbe019d596e5e8c2f499e2fc6873d0ac67
