### ISSUE TITLE
evolven3fit_new problem in reading metadata.yaml?

### ISSUE THREAD

**Issue by comane** [NNPDF/nnpdf#1706]
(DISCLAIMER: this might not be a true issue but just my limited knowledge of eko.)
@AleCandido , @andreab1997 , @scarlehoff  When trying to evolve a (theory 200) fit (that has been already evolved with evolven3fit) with `evolven3fit_new`, I get the following (I tried to use the theory 400 eko and got the same)

error message:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpnby3_wdk/metadata.yaml'

The whole error message is:

$ evolven3fit_new evolve DIS_only_closure_L2_HERACOMB_ADD_as_01180 --force

2023-03-23 12:07:16,676 evolven3fit_new.evolve/INFO: Loading eko from theory 200
Traceback (most recent call last):
  File "/home/mnc33/rds/hpc-work/miniconda3/envs/nnpdf-dev/bin/evolven3fit_new", line 33, in <module>
    sys.exit(load_entry_point('n3fit', 'console_scripts', 'evolven3fit_new')())
  File "/rds/user/mnc33/hpc-work/codes/nnpdfgit/nnpdf/n3fit/src/n3fit/scripts/evolven3fit_new.py", line 123, in main
    cli.cli_evolven3fit_new(
  File "/rds/user/mnc33/hpc-work/codes/nnpdfgit/nnpdf/n3fit/src/evolven3fit_new/cli.py", line 32, in cli_evolven3fit_new
    return evolve.evolve_fit(
  File "/rds/user/mnc33/hpc-work/codes/nnpdfgit/nnpdf/n3fit/src/evolven3fit_new/evolve.py", line 99, in evolve_fit
    with eko.EKO.edit(eko_path) as eko_op:
  File "/home/mnc33/rds/hpc-work/miniconda3/envs/nnpdf-dev/lib/python3.9/site-packages/eko/io/struct.py", line 923, in edit
    eko = cls.open(path, "a")
  File "/home/mnc33/rds/hpc-work/miniconda3/envs/nnpdf-dev/lib/python3.9/site-packages/eko/io/struct.py", line 877, in open
    metadata = Metadata.load(tmpdir)
  File "/home/mnc33/rds/hpc-work/miniconda3/envs/nnpdf-dev/lib/python3.9/site-packages/eko/io/struct.py", line 440, in load
    yaml.safe_load(InternalPaths(path).metadata.read_text(encoding="utf-8"))
  File "/home/mnc33/rds/hpc-work/miniconda3/envs/nnpdf-dev/lib/python3.9/pathlib.py", line 1266, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/home/mnc33/rds/hpc-work/miniconda3/envs/nnpdf-dev/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/home/mnc33/rds/hpc-work/miniconda3/envs/nnpdf-dev/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpnby3_wdk/metadata.yaml'

**Comment by AleCandido** [comment]
Theories at the moment contain old format EKOs, that didn't contain `/metadata.yaml` files.

@andreab1997 is working to update them.

**Comment by RoyStegeman** [comment]
I guess this can be closed? Or alternatively made a more general issue regarding the things that need to be updated for theories 400 and beyond.
